{{- if or .Values.auth.enabled (not .Values.auth.existingSecret) }}
{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rustatio.fullname" . }}
  labels:
    {{- include "rustatio.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.token }}
  AUTH_TOKEN: {{ .Values.auth.token | b64enc }}
  {{- else }}
  {{- $token := randAlphaNum 64 }}
  AUTH_TOKEN: {{ $token | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
